### ISSUE TITLE
支持android系统使用

### ISSUE THREAD

**Issue by zzw8421** [CodePhiliaX/easyexcel-plus#12]

**Comment by meofme** [comment]
Looking forward to supporting Android system

**Comment by 121104115wyb** [comment]
Looking forward to supporting Android system

**Comment by delei** [comment]
We currently do not have an Android environment to verify this.Could you share any errors you’ve encountered during actual usage?

当前我们没有 Android 环境来验证，能否提供一些在使用过程中出现的具体错误信息?

**Comment by tuuzed** [comment]
Caused by: cn.idev.excel.exception.ExcelGenerateException: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/font/FontRenderContext;
	at cn.idev.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:65)
	at cn.idev.excel.ExcelWriter.write(ExcelWriter.java:73)
	at cn.idev.excel.ExcelWriter.write(ExcelWriter.java:50)
	at cn.idev.excel.write.builder.ExcelWriterSheetBuilder.doWrite(ExcelWriterSheetBuilder.java:62)

和POI streaming APIs 一样依赖 awt

**Comment by delei** [comment]
> Caused by: cn.idev.excel.exception.ExcelGenerateException: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/font/FontRenderContext; at cn.idev.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:65) at cn.idev.excel.ExcelWriter.write(ExcelWriter.java:73) at cn.idev.excel.ExcelWriter.write(ExcelWriter.java:50) at cn.idev.excel.write.builder.ExcelWriterSheetBuilder.doWrite(ExcelWriterSheetBuilder.java:62)
> 
> 和POI streaming APIs 一样依赖 awt

Thank you for your feedback. 

As far as I know, in the Android development environment, it seems that POI cannot be directly used too. Since the project currently relies on Apache POI. Without additional contributors or POIs to support this effort, it may not be possible to address this issue in the near term.

**Comment by alaahong** [comment]
@zzw8421  @meofme @121104115wyb @tuuzed  can you provide the code sample to understand specific scenario of exception?

Based on above error message, seems it caused by missed java.awt.* on Android environment. Might be you can try to work with FastExcel without font relatives., e.g. disable auto width.

Also welcome to reply the exception details.

**Comment by SageJustus** [comment]
```kotlin
FastExcel.write(file, SomeThing::class.java)
        .registerWriteHandler(SimpleColumnWidthStyleStrategy(20)) 
        .useDefaultStyle(false)
        .sheet("something")
        .doWrite(records)
```
How to `disable auto width` ? I used the code provided above, but the error still occurs. @alaahong 
```
2026-02-22 14:40:45.449 29649-29726 System.err              com.sage.android                     W  cn.idev.excel.exception.ExcelGenerateException: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/font/FontRenderContext;
2026-02-22 14:40:45.449 29649-29726 System.err              com.sage.android                     W  	at cn.idev.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:63)
2026-02-22 14:40:45.449 29649-29726 System.err              com.sage.android                     W  	at cn.idev.excel.ExcelWriter.write(ExcelWriter.java:70)
2026-02-22 14:40:45.449 29649-29726 System.err              com.sage.android                     W  	at cn.idev.excel.ExcelWriter.write(ExcelWriter.java:47)
2026-02-22 14:40:45.449 29649-29726 System.err              com.sage.android                     W  	at cn.idev.excel.write.builder.ExcelWriterSheetBuilder.doWrite(ExcelWriterSheetBuilder.java:76)
2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at com.sage.android.ui.screen.VideoViewModel$exportToExcel$1.invokeSuspend(VideoViewModel.kt:58)
2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/font/FontRenderContext;
2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at org.apache.poi.ss.util.SheetUtil.<clinit>(SheetUtil.java:99)
2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at org.apache.poi.xssf.streaming.AutoSizeColumnTracker.<init>(AutoSizeColumnTracker.java:119)
2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at org.apache.poi.xssf.streaming.SXSSFSheet.<init>(SXSSFSheet.java:106)
2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createAndRegisterSXSSFSheet(SXSSFWorkbook.java:697)
2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:715)
2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:107)
2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at cn.idev.excel.util.WorkBookUtil.createSheet(WorkBookUtil.java:96)
2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at cn.idev.excel.context.WriteContextImpl.createSheet(WriteContextImpl.java:258)
2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at cn.idev.excel.context.WriteContextImpl.initSheet(WriteContextImpl.java:234)
2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at cn.idev.excel.context.WriteContextImpl.currentSheet(WriteContextImpl.java:151)
2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at cn.idev.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:52)
2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	... 12 more
2026-02-22 14:40:45.451 29649-29726 System.err              com.sage.android                     W  Caused by: java.lang.ClassNotFoundException: Didn't find class "java.awt.font.FontRenderContext" on path: DexPathList[[dex file "/data/data/com.sage.android/code_cache/.overlay/base.apk/classes7.dex", zip file "/data/app/~~vcTsncLlaDpUz9aVALyxpw==/com.sage.android-6K1Ei5xjDB-i9PCBHMqIxQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~vcTsncLlaDpUz9aVALyxpw==/com.sage.android-6K1Ei5xjDB-i9PCBHMqIxQ==/lib/arm64, /data/app/~~vcTsncLlaDpUz9aVALyxpw==/com.sage.android-6K1Ei5xjDB-i9PCBHMqIxQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
2026-02-22 14:40:45.451 29649-29726 System.err              com.sage.android                     W  	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
2026-02-22 14:40:45.451 29649-29726 System.err              com.sage.android                     W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
2026-02-22 14:40:45.451 29649-29726 System.err              com.sage.android                     W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
2026-02-22 14:40:45.451 29649-29726 System.err              com.sage.android                     W  	... 23 more
```

**Comment by alaahong** [comment]
> FastExcel.write(file, SomeThing::class.java)
>         .registerWriteHandler(SimpleColumnWidthStyleStrategy(20)) 
>         .useDefaultStyle(false)
>         .sheet("something")
>         .doWrite(records)
> How to `disable auto width` ? I used the code provided above, but the error still occurs. [@alaahong](https://github.com/alaahong)
> 
> ```
> 2026-02-22 14:40:45.449 29649-29726 System.err              com.sage.android                     W  cn.idev.excel.exception.ExcelGenerateException: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/font/FontRenderContext;
> 2026-02-22 14:40:45.449 29649-29726 System.err              com.sage.android                     W  	at cn.idev.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:63)
> 2026-02-22 14:40:45.449 29649-29726 System.err              com.sage.android                     W  	at cn.idev.excel.ExcelWriter.write(ExcelWriter.java:70)
> 2026-02-22 14:40:45.449 29649-29726 System.err              com.sage.android                     W  	at cn.idev.excel.ExcelWriter.write(ExcelWriter.java:47)
> 2026-02-22 14:40:45.449 29649-29726 System.err              com.sage.android                     W  	at cn.idev.excel.write.builder.ExcelWriterSheetBuilder.doWrite(ExcelWriterSheetBuilder.java:76)
> 2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at com.sage.android.ui.screen.VideoViewModel$exportToExcel$1.invokeSuspend(VideoViewModel.kt:58)
> 2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
> 2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
> 2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
> 2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
> 2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
> 2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
> 2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
> 2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/font/FontRenderContext;
> 2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at org.apache.poi.ss.util.SheetUtil.<clinit>(SheetUtil.java:99)
> 2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at org.apache.poi.xssf.streaming.AutoSizeColumnTracker.<init>(AutoSizeColumnTracker.java:119)
> 2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at org.apache.poi.xssf.streaming.SXSSFSheet.<init>(SXSSFSheet.java:106)
> 2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createAndRegisterSXSSFSheet(SXSSFWorkbook.java:697)
> 2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:715)
> 2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:107)
> 2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at cn.idev.excel.util.WorkBookUtil.createSheet(WorkBookUtil.java:96)
> 2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at cn.idev.excel.context.WriteContextImpl.createSheet(WriteContextImpl.java:258)
> 2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at cn.idev.excel.context.WriteContextImpl.initSheet(WriteContextImpl.java:234)
> 2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at cn.idev.excel.context.WriteContextImpl.currentSheet(WriteContextImpl.java:151)
> 2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	at cn.idev.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:52)
> 2026-02-22 14:40:45.450 29649-29726 System.err              com.sage.android                     W  	... 12 more
> 2026-02-22 14:40:45.451 29649-29726 System.err              com.sage.android                     W  Caused by: java.lang.ClassNotFoundException: Didn't find class "java.awt.font.FontRenderContext" on path: DexPathList[[dex file "/data/data/com.sage.android/code_cache/.overlay/base.apk/classes7.dex", zip file "/data/app/~~vcTsncLlaDpUz9aVALyxpw==/com.sage.android-6K1Ei5xjDB-i9PCBHMqIxQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~vcTsncLlaDpUz9aVALyxpw==/com.sage.android-6K1Ei5xjDB-i9PCBHMqIxQ==/lib/arm64, /data/app/~~vcTsncLlaDpUz9aVALyxpw==/com.sage.android-6K1Ei5xjDB-i9PCBHMqIxQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
> 2026-02-22 14:40:45.451 29649-29726 System.err              com.sage.android                     W  	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
> 2026-02-22 14:40:45.451 29649-29726 System.err              com.sage.android                     W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
> 2026-02-22 14:40:45.451 29649-29726 System.err              com.sage.android                     W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
> 2026-02-22 14:40:45.451 29649-29726 System.err              com.sage.android                     W  	... 23 more
> ```

How about replace poi-ooxml with poi-ooxml-lite? seems it's used to work with Android's JVM.
